name: Validate Proposed DNS Records

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - "domains.json"
      - "scripts/**"

jobs:
  validate-dns:
    name: Publish Records
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"

      - name: Install Node.js dependencies
        run: yarn install --frozen-lockfile

      - name: Run Validater
        run: yarn check:domains
